name: 'e2e'
on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12]
        include:
          - os: macos-latest
            node_version: 12
      fail-fast: false
    name: 'e2e: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-node${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node_version }}-

      - name: Versions
        run: yarn versions

      - name: Install dependencies and verify Cypress
        run: yarn install --frozen-lockfile

      - name: Build
        run: npm run build uni-app uni-cli-shared uni-h5 uni-i18n uni-shared vite-plugin-uni

      - name: Install ssr
        working-directory: ./packages/playground/ssr
        run: |
          yarn install --frozen-lockfile
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: true
          start: npm run e2e:ssr:dev
          project: ./packages/playground/ssr
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
