name: 'size'
on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1

      - uses: posva/size-check-action@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          files: packages/uni-h5-vue/dist/vue.runtime.esm.js packages/uni-mp-alipay/dist
